name: Wade Stratagem
favicon: null
layout_spectrum: 0.25165
typography_spectrum: 0.46746
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75735513-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f2f2f2'
    - '#b6b6b6'
    - '#464646'
    - '#838383'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
