name: Wade Stratagem
favicon: null
layout_spectrum: 0.24772
typography_spectrum: 0.994855708675459
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010000'
    - '#ffffff'
    - '#3fa74b'
    - '#605f5f'
    - '#cbcbcb'
  brandStrength: 0.12598185404203832
  lightness: 0.6311315507628024
  saturation: 0.10616666032001376
  rhythmicContrast: 0.1554239448159933
purpose: []
