name: Wade Stratagem
favicon: null
layout_spectrum: 0.25165
typography_spectrum: 0.46746
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f2f2f2'
    - '#b6b6b6'
    - '#5f5f5f'
    - '#3e8846'
  brandStrength: 0.9375
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
